version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
  - dependency-name: eslint-plugin-testing-library
    versions:
    - 4.0.0
    - 4.0.1
    - 4.1.0
    - 4.1.1
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.0
    - 12.7.2
    - 12.7.3
    - 13.0.10
    - 13.0.13
    - 13.0.7
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: react-scripts
    versions:
    - 4.0.3
